### PR TITLE
readme: Fix contact link

### PR DESCRIPTION
**Pull request by KaitoKid**
Updated the contact link on the readme to reflect quilt.io changes

### CODE REVIEW

**Comment by kklin** [comment]
Ah, @KaitoKid I also realized that your commit only includes your name, but not email.

**Comment by kklin** [comment]
By the way, @KaitoKid, I could make the changes if you're busy with finals! Just let me know :)

**Comment by KaitoKid** [comment]
@kklin Oops, missed that! First time submitting a pull req and didn't realize there was a guideline for it. Fixed it, thanks!

**Comment by kklin** [comment]
No problem @KaitoKid, we're somewhat more stringent about our commit history than others 😄.

It actually looks like you only edited the PR title, but not the commit itself. To edit the commit, you should do something along the lines of `git checkout fixed-contact-link`, then `git commit --amend` and edit the message, and then `git commit --amend --author="Kairui Zeng <kairui@kairuizeng.com>"` to add your email address. You can set your email permanently for all future commits by following https://help.github.com/articles/setting-your-email-in-git/.

**Comment by KaitoKid** [comment]
@kklin Alright.. I think I got it this time around.

1. Fixed global email to be my github email
2. Changed the commit message
2a. At this point, I tried to [re-push to update commit message](https://help.github.com/articles/changing-a-commit-message/) but had a [weird error](http://i.imgur.com/UdnPXuY.png) come up so...
3. Re-pulled (and edited the merge message to be the commit message) so that I can re-commit and then

**Comment by ejj** [comment]
@KaitoKid, That error is somewhat expected when you're fixing up a PR.  Its complaining that you've edited a commit instead of just adding new commits, which is fine as that's exactly what you've intended to do.  You can git around the error by doing `git push --force` after you've fixed up your commit history.  Btw, you may want to look into `git rebase` if you need to tweak the history.

Thanks!

**Comment by kklin** [comment]
@KaitoKid I went ahead and fixed up the history, and merged the commit. Thanks!

**Pull request closed without merging**
