### PR TITLE
Refactor NAT logic

### PR DESCRIPTION
**Pull request by kklin**

### CODE REVIEW

**Comment by kklin** [comment]
@LuiseV do you have time to review this in the next day or two? I'd like to get it in fast as it blocks Digitalocean. We could assign it to someone else if you're busy.

**Comment by LuiseV** [comment]
Yes, I can review it today or tomorrow!

**Comment by kklin** [comment]
Not sure why quilt-bot assigned you @ejj, but can you skim this commit? https://github.com/quilt/quilt/pull/794/commits/00ae4563b86d1ee40e2f83ab84d9862960752052

In particular, I want to make sure you're OK with the approach of installing "default rules" and "prerouting rules": https://github.com/quilt/quilt/pull/794/commits/00ae4563b86d1ee40e2f83ab84d9862960752052#diff-47a66ada7d55780d3bc7d9fc374099a2R50

**Comment by kklin** [comment]
Talked to @ejj, he said it looked fine.

**Pull request merged**
