### PR TITLE
minor: Fix typo in comment

### PR DESCRIPTION
**Pull request by kayousterhout**

### CODE REVIEW

**Comment by kklin** [comment]
(cc @ejj)

We haven't used this `minor` category before, but I kind of like it. (I think before, we would have used `quilt: ...` because it's in `quilt.go`). Worth discussing if we should make this a standard.

**Comment by kayousterhout** [comment]
One other alternative is "docs:" -- but I like minor as a signal to people skimming the commits that it's safe to ignore

**Comment by kklin** [comment]
I'd like to save docs for our documentation folder (or is that getting moved?)

**Comment by kayousterhout** [comment]
Makes sense (and it won't get moved)

**Comment by ejj** [comment]
I don't particularly have an opinion on the minor thing.  I likely won't use it, but I think its fine.

**Pull request merged**
