### PR TITLE
Rename quilt-tester to integration-tester

### PR DESCRIPTION
**Pull request by kayousterhout**
As suggested by Ethan today (this is generally useful but also nice to do before we rename the whole project, since it's one fewer rename to do)

### CODE REVIEW

**Comment by kayousterhout** [comment]
Any idea why the code coverage went down so much?

**Comment by kayousterhout** [comment]
Is this because the old travis config is being used here, so it thinks integration-tester is not being tested?

**Comment by kklin** [comment]
We actually don't want to include the integration tester in the codecov. https://github.com/quilt/quilt/blob/master/.codecov.yaml#L26

**Comment by kayousterhout** [comment]
Cool thanks Kevin your comment made me realize I had a typo in my re-naming of the excluded directory in .codecov.yaml

**Comment by kklin** [comment]
@kayousterhout can you rebase, and open a PR for renaming the github.com/quilt/tester repo as well? If we merge this PR now, Jenkins will still try to look for the tests in the `quilt-tester` directory, and fail.

**Comment by kayousterhout** [comment]
Done: https://github.com/quilt/tester/pull/51

**Pull request merged**
