### PR TITLE
ovs: Bundle newest DigitalOcean kernel version

### PR DESCRIPTION
**Pull request by kklin**
The Ubuntu image provided by DigitalOcean now uses the linux kernel
version 4.4.0-81.

### CODE REVIEW

**Comment by kklin** [comment]
The auto-build worked, I just noticed the machines took longer than usual to connect (6 minutes).

**Comment by Baisang** [comment]
I think we've gone past the vagrant kernel version we've pinned a while ago. Would we want to update either?

**Comment by Baisang** [comment]
I.e our ovs docker file version > the version in the pinned vagrant box

**Comment by kklin** [comment]
I think the Vagrant version is pinned to `4.4.0-62` (as is Amazon and Google).

**Comment by Baisang** [comment]
Oh I think you're right, I remember now. I had specifically found that version to make sure it was the same as the Amazon and Google ones.

**Pull request merged**
